### ISSUE TITLE
[Android] onInstallConversionData callback always return organic result

### ISSUE THREAD

**Issue by johnkennethfurog** [AppsFlyerSDK/appsflyer-react-native-plugin#168]
**What I'm trying to do**
I tried to get the convention data (deferred deep linking) via onInstallConversionData callback

**What I've done**

Click the following Onelink:
// Short version
https://street-food-guru.onelink.me/BhN9/7acb7582

// Long version
https://street-food-guru.onelink.me/BhN9?pid=Furog&is_retargeting=true&c=Coupon%20Event&af_sub1=0001

- Got re-directed to the Google Play Store
- Install the app using adb install command
- Open the app

**Expected result**
onInstallConversionData called with the non-organic result (pid=dailydeals), af_dp=eatsy://highlight-details?highlightID=6

**Actual result**
onInstallConversionData called with the following data: {"af_status":"Organic","af_message":"organic install","is_first_launch":"true"}

Screenshot wit the pid and af_status highlighted:
<img width="1498" alt="Appsflyer Screenshot 1" src="https://user-images.githubusercontent.com/26668051/88562095-d9f05480-d062-11ea-93f7-efc35e38e0d5.png">

<img width="866" alt="Appsflyer Screenshot 2" src="https://user-images.githubusercontent.com/26668051/88562324-20de4a00-d063-11ea-9ff1-af0a28d4235a.png">

**Additional Information**

- Despite the onInstallConversionData got called with organic result on the device, the install count still tracked correctly on the Dashboard:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/26668051/88562576-70247a80-d063-11ea-896c-7fe68cb87c02.png">

- The device was whitelisted
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26668051/88562733-a3ffa000-d063-11ea-9e49-0252b5302261.png">

**Versions**
"react-native": "0.62.1"
"react-native-appsflyer": "^^5.4.1"

**Comment by af-vs** [comment]
Hi @johnkennethfurog!

Thank you for reporting this!

I can see that install was attributed to the main version of the app `com.streetfoodguru` while conversion data is requested for the out-of-store version of the app `com.streetfoodguru-StreetFoodGuru`.

At the same time, I can see that the install payload sent by the SDK contains the channel parameter properly.

Based on the above I don't have a reason to believe there is an issue in the SDK implementation or the SDK itself. Thus, if the issue persists, please open a ticket to our Customer Support Team at support@appsflyer.com and refer to this thread so that they can investigate this properly.

Thank you!

**Comment by johnkennethfurog** [comment]
hi @af-vs 

by saying:

> I can see that install was attributed to the main version of the app `com.streetfoodguru` while conversion data is requested for the out-of-store version of the app `com.streetfoodguru-StreetFoodGuru`.
> 

what does it mean ?

thanks

**Comment by af-vs** [comment]
@johnkennethfurog I can see you have created 2 different dashboards for the same app. Usually, it is being done in case you distribute the same app in multiple stores. You can read more about it [here](https://support.appsflyer.com/hc/en-us/articles/207447023-Setting-up-multi-store-Android-attribution-).

Conversion data was requested for the out of store version of the app (with the channel) however non-organic install was recorded under the main version of the app. You got default organic conversion data because AppsFlyer couldn't find your install under out-of-store version of the app.

If any clarification is needed, please ask your Customer Success Manager or Support for further info as the issue doesn't seem to be related to the SDK itself. If any issue with the SDK will be found by our support team, they will make sure to loop in RnD.

Thank you!

**Comment by johnkennethfurog** [comment]
@af-vs 

thank you for this ! 👍
