### ISSUE TITLE
onAppOpenAttribution not called with app in background

### ISSUE THREAD

**Issue by lucasaugustin** [AppsFlyerSDK/appsflyer-react-native-plugin#183]
# Report

## Plugin Version
5.2.0

## On what Platform are you having the issue?
ios

## What did you do?
with app in background,  click on onelink.

## What did you expect to happen?
App to be open, and call `onAppOpenAttribution`.

## What happened instead?
App was opened, but `onAppOpenAttribution` was not called.

## Please provide any other relevant information.
I have copy-pasted the hooks deeplink example. It works as expected on android, but on ios it only call `onAppOpenAttribution` if the app is closed (killed).

I have used diferent links to avoid this:  https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/119

**Comment by af-vs** [comment]
Hi @lucasaugustin!

On version 5.2.0 it is required to trigger trackAppLaunch every time the app moves from background to foreground. It is described in the guide for the relevant version - https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/v5.2.0/Docs/Guides.md#init-sdk
![image](https://user-images.githubusercontent.com/50541317/93458236-ba4e0d80-f8e8-11ea-8ab3-933969053d7b.png)

However in the next version, we have moved this logic inside the plugin, so if you update the version you don't need this extra step, that's why it is now missing from the docs
![image](https://user-images.githubusercontent.com/50541317/93458325-d6ea4580-f8e8-11ea-86c0-c09b6b4cbe55.png)

Let me know if that answers your question/solves the issue

**Comment by lucasaugustin** [comment]
This seems to resolve the problem. Thanks!!
