### ISSUE TITLE
[Android] disableAdvertisingIdentifier and disableCollectASA cause fatal errors

### ISSUE THREAD

**Issue by curiousdustin** [AppsFlyerSDK/appsflyer-react-native-plugin#202]
# Report

## Plugin Version

6.0.50

## On what Platform are you having the issue?

Android

## What did you do?

Using either of the following without protecting them from running on Android causes fatal errors:
```
appsFlyer.disableAdvertisingIdentifier(true);
appsFlyer.disableCollectASA(true);
```

## What did you expect to happen?

It would be nice if it just simply did nothing, maybe with a warning, instead of causing your app to crash.

## What happened instead?

App crash

## Please provide any other relevant information.

I realize that it is documented that these are iOS only. However, it seems like at the very least it should not crash. A Warning would be nice.

**Comment by amit-kremer93** [comment]
Hi @curiousdustin thank you for opening this issue and i'm sorry for your bad experience.
In order to prevent the android app to crash you should use these api inside
`if (Platform.OS =="iOS"){
appsFlyer.disableAdvertisingIdentifier(true);
appsFlyer.disableCollectASA(true);
}`
block.
We will update the docs and fix this crash.
