### ISSUE TITLE
"Sending `onInstallConversionDataLoaded` with no listeners registered" after upgrading to react-native 0.63 and AppsFyler SDK to 6.0.50

### ISSUE THREAD

**Issue by arrygoo** [AppsFlyerSDK/appsflyer-react-native-plugin#211]
# Report

## Plugin Version
^6.0.50

## On what Platform are you having the issue?
React Native - ios

## What did you do?
I had AppsFlyer SDK working in a react-native 0.62 app, then I upgraded RN to 0.63 and AppsFlyer to `^6.0.50`, I get the error below on start.

## What did you expect to happen?
AppsFlyer SDK to continue working and capturing install event

## What happened instead?
I get an error on start saying `Sending `onInstallConversionDataLoaded` with no listeners registered.`

## Please provide any other relevant information.
I did clear `DerivedData`, build folder, `node_modules`, and cleaned all relevant caches using `react-native clean-project-auto`. Android works perfectly after the update, but iOS gives the error above.

I also tried moving the AppsFlyer `init` from my `App.tsx` to my `index.js` thinking it needs to initialize earlier, but that didn't fix the error above.

**Comment by amit-kremer93** [comment]
Hi @arrygoo thank you for opening this issue.
i will check it and get back to you

**Comment by arrygoo** [comment]
Thank you @amit-kremer93 . Let me know if I can do anything on my side to debug it further or narrow down the problem.

**Comment by arrygoo** [comment]
@amit-kremer93 FYI I just updated to `AppsFlyerFramework (6.1.1.)` and `react-native-appsflyer (6.1.10)`, but I still have the same problem. I also tried completely removing appsflyer and adding it again to the project, but it didn't help. 

This is a blocker for our next release, I was wondering if you can kindly point me towards areas I can look at in AppsFlyer's sdk code to debug this further. 

Thanks in advance!

**Comment by amit-kremer93** [comment]
Hi @arrygoo, did you set `onInstallConversionDataListener` in the object that goes to `appsflyer.initSdk`?
if you don't set it, the default is `onInstallConversionDataListener=true`, and if you don't registered listeners as explained [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#direct-deep-linking)
you will get this error.
try to set `onInstallConversionDataListener=false` and please let me know if it helped.

**Comment by arrygoo** [comment]
Hey @amit-kremer93 ,

Setting `onInstallConversionDataListener` to false makes the warning go away. What are the implication of this flag though? Will it stop capturing install events? I did look at the documentation saying `Set listener for SDK init response` but I still don't fully understand that flag. Is it an event that fires once the SDK has been initialized and has nothing to do with app installs?

**Comment by amit-kremer93** [comment]
Hey @arrygoo. this flag tells the sdk to register a conversion listener for app launch events: first launch, onAppOpenAttribution or just a simple launch, as you can see [Here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/4ca80da473b794dc254aa7afe55e3f16e6d8f87b/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java#L139) and you can read more about conversion data [Here](https://support.appsflyer.com/hc/en-us/articles/360000726098-Get-conversion-data-using-AppsFlyer-SDK#introduction).
if you set this flag to false, the sdk will not send the type and the details of the launch(first install, simple launch etc.) back to the react-native side, but beside that the sdk will continue to work as usual.
I agree that the name of this flag is a bit confusing because its not related only to installs.
if you have more questions related to the sdk, please contact our support: support@appsflyer.com
