### ISSUE TITLE
IDFA Tracking Using V6

### ISSUE THREAD

**Issue by af2446** [AppsFlyerSDK/appsflyer-react-native-plugin#240]
Hi.
My name is aviv and I'm an iOS developer which is using your SDK product.
I have a couple of questions regarding the migration to V6 which the documentation did not include.

1. does the function "waitForATTUserAuthorization(timeoutInterval: 60)" start counting when i call it, or when the app is launched or maybe when i call for "ATTrackingManager.requestTrackingAuthorization"?.

2. Does your SDK have a way to update the IDFA parameter manually after I receive it through the AdSupport framework?, 
i do not want to be dependent on a timer which I'm not sure what he's doing

**Comment by amit-kremer93** [comment]
Hi @af2446 , you can read [here](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#additional-apis-support-apptrackingtransparency-att) for more info, or you can ask our support team in order to get a more detailed explanation: support@appsflyer.com
