### ISSUE TITLE
Failed to connect to inapps.appsflyer.com/:::443

### ISSUE THREAD

**Issue by YanisKondakov** [AppsFlyerSDK/appsflyer-react-native-plugin#311]
# Report

## Plugin Version

`6.3.20`

## On what Platform are you having the issue?

Android

## What did you do?

Launch application and init sdk via
`appsFlyer.initSdk({
    devKey: ****,
    isDebug: false,
});`

## What did you expect to happen?

AppsFlyer successfully connect to server

## What happened instead?

AppsFlyer log error about problem with connection
There are our two Sentry reports
1) [Error: Failed to connect to inapps.appsflyer.com/:::443](https://sentry.agreatpieceofcluster.com/share/issue/e2726212c13b46b7bce7305b400dd8d9/)

2) [Error: Failed to connect to inapps.appsflyer.com/0.0.0.0:443](https://sentry.agreatpieceofcluster.com/share/issue/de6cc36770e043788fbcbd1d6453ea01/)

## Please provide any other relevant information.

We have hundreds error events in our sentry reports. This error started two months ago. Also we have no more full statistic in our AppsFlyer dashboards.

**Comment by anshzinc** [comment]
Facing same issue our in production application.

**Comment by ge-af** [comment]
Hi all,

This issue looks related to internet connection issues. 
This is usually a networking problem on the device itself and not so related to the SDK specifically. It seems this is a DNS issue, it unable to resolves the hostname to the proper IP address and that's why the IP is not assigned (0.0.0.0).

**Comment by artyorsh** [comment]
Hi @ge-af :wave:
 
I would agree with your conclusion, but actually this issue wasn't a problem for our ~20k users project 3 month ago. We were using v6.2.60 that time and keeping the dependency up-to-date since then. Now, this report is always on top of the Sentry / Firebase / whatever else bug tracking system table. Furthermore:

> This issue looks related to internet connection issues.

The app is used to send multiple HTTP requests during the start time, including the appsflyer initialization and conversion data retrieval. It works OK, but produces these `failed to connect` errors for some reason.

Please investigate, since several bug tracking systems has limited amount of trackable errors in its free plans, meaning the smaller projects may suffer from such type of issues. Thank you.

**Comment by ge-af** [comment]
Hi @artyorsh 

Thanks for your valuable feedback!

I'm checking it again with our R&D and DevOps teams to see if there were any changes on our side regarding any DNS or Server issues that may have started in the last few weeks/months.

Can you please notice if there is something specific regarding the users who gets this networking errors (if possible) - Any specific regions/countries or any specific Android OS versions this is coming from?

If possible also to list of possible exception occurrences of this error (SSLException, SSLHandshakeException, etc.) that may be visible under any Analytics provider (Sentry, Firebase Crashlytics, etc.) and I'll forward it to our R&D team to further investigate.

**Comment by artyorsh** [comment]
Thank you for the quick response @ge-af 

> Any specific regions/countries

The app is limited to run in Germany.
I'm not sure the error report can be informative in this case, since its stack trace doesn't show anything interesting. However, see [the link](https://sentry.io/share/issue/a33abd5b71ed40da8fe9dd1b1a3227f6). This one was reported ~30k times during last 3 months.

I can't be sure it could be related to the region since I also see the error occurs also in Belarus in our dev environment. [See report](https://sentry.io/share/issue/a33abd5b71ed40da8fe9dd1b1a3227f6). In some occurencies it's reported with `Unable to resolve host "inapps.appsflyer.com": No address associated with hostname` message.

> any specific Android OS versions

It's mostly reported on Android. Unfortunately, there is no specific OS version where this issue occurs. On iOS however I may suppose that it is reported with a different message. Supposedly, `Network failure`.

There is one more interesting report I found while reviewing the whole error table (Android 9, Samsung SM-G950F): https://sentry.io/share/issue/e0e217226eaa450597a82a85af101709

I'll check these errors in detail to see if I can find anything else from there.

**Comment by ge-af** [comment]
Hi @artyorsh 

We tried to test it from Belarus and Germany and got the DNA resolution and everything is working on our side.
Do you have any way to identify which **ISP/Mobile carriers** are being used by the users with those faulty errors? If so, we can continue to try and take it with AWS Support.

**Comment by bondanherumurti** [comment]
Hi I'm also facing this issue mostly
Failed to connect to inapps.appsflyer.com/0.0.0.0:443
Unable to resolve host "inapps.appsflyer.com": No address associated with hostname
Error: com.appsflyer.sdk.network

My app resides on Indonesia, some of them using wifi broadband or mobile... It looks like the DNS not propagated properly on some ISP.

Here some ISP/Mobile Carriers from my IP Tracing
PT Telkom Indonesia (Major Mobile Provider in Indonesia)
PT Data Buana Nusantara
Biznet Networks
PT Indosat (Major Telco In Indonesia)
PT Gayatri Lintas Nusantara
PT. Eka Mas Republik

Non Indonesia ISP
The University of Edinburgh

The experiences are not consistent because some of user (our tester) with the ISP mentioned above did not experience the error. It really looks like a unfinished/unproper DNS propagation


Cheers

**Comment by pebehb** [comment]
I would not agree to close this issue. We have the same in Sentry logs
It started to appear a year ago. And now we have 223k error events in Sentry logs about that.
Right now we're using version 6.3.50 with RN 0.60.5
The most OS appeared is Android, few on iOs
Users mostly from US

**Comment by eatnug** [comment]
I was facing same issue on react-native 0.62.2 and react-native-appsflyer 6.4.0 in South Korea.

Sentry shows 2 different message like others.

- `Unable to resolve host "inapps.appsflyer.com": No address associated with hostname`
- `Failed to connect to inapps.appsflyer.com/0.0.0.0:443`

I still don't know what's causing that issue but it seems changing targetSdkVersion to 30 dramatically lowered the occurence of this error.

**Comment by dimadeveatii** [comment]
We also see this issue happening sometimes, on both platforms, Android and iOS. 
We believe this is due to a network error.  

**Question**: is the sdk supposed to work in offline mode? Suppose I'm offline, track some events, then return to the app in an hour with stable network connection. Will appsflyer re-submit the failed events?

**Comment by pebehb** [comment]
> 
> 
> We also see this issue happening sometimes, on both platforms, Android and iOS. We believe this is due to a network error.
> 
> **Question**: is the sdk supposed to work in offline mode? Suppose I'm offline, track some events, then return to the app in an hour with stable network connection. Will appsflyer re-submit the failed events?

Agree with you: there is network issue.

I have another question: should this affect on my App or not ? I believe - NOT

**Comment by diegodorado** [comment]
Which is the network issue exactly?

Because on our logs our app is able to do a codepush update, and fetch from our API mutliple times with 200 status responses before getting this error or this other one:
```
error: Unable to resolve host "inapps.appsflyer.com": No address associated with hostname, 

```

**Comment by djw27** [comment]
We're seeing multiple variations of this at really high rates which can't really be explained by internet connectivity issues as the error is preceded by successful requests to other APIs in our case.

Variations we're seeing:

`Unable to resolve host "inapps.appsflyer.com": No address associated with hostname`
`Failed to connect to inapps.appsflyer.com/0.0.0.0:443`
`Failed to connect to inapps.appsflyer.com/:::443`

**Comment by rusakovic** [comment]
Confirm the issue.
Should be reopened

```
Error: Failed to connect to inapps.appsflyer.com/0.0.0.0:443
```
"react-native-appsflyer": "^6.5.20"

**Comment by anuragshahi9911** [comment]
Same issue for me too. 

Error: Failed to connect to inapps.appsflyer.com/:::443

Because of this issue events are not reflected on the AppsFlyer dashboard. 

I am using 
"@ionic-native/appsflyer": "^5.16.0",
"cordova-plugin-appsflyer-sdk": "^6.3.0",

Did not see any resolution for this anywhere. Is this issue closed?

**Comment by raquel-nobre** [comment]
> Olá a todos,
> 
> Esse problema parece relacionado a problemas de conexão com a Internet. Isso geralmente é um problema de rede no próprio dispositivo e não está relacionado especificamente ao SDK. Parece que este é um problema de DNS, incapaz de resolver o nome do host para o endereço IP adequado e é por isso que o IP não é atribuído (0.0.0.0).
would it be possible to check if the user has internet before the error is triggered?
I'm having the same problem.

Failed to connect to inapps.appsflyer.com/0.0.0.0:443

**Comment by raquel-nobre** [comment]
> Hi all,
> 
> This issue looks related to internet connection issues. This is usually a networking problem on the device itself and not so related to the SDK specifically. It seems this is a DNS issue, it unable to resolves the hostname to the proper IP address and that's why the IP is not assigned (0.0.0.0).



would it be possible to check if the user has internet before the error is triggered?
I'm having the same problem.

Failed to connect to inapps.appsflyer.com/0.0.0.0:443

**Comment by DominicTobias** [comment]
I have checked that Segment is using the correct App IDs and AppsFlyer devkey but also getting 1000s of these errors, all other network requests are fine 🤔

**Comment by givehug** [comment]
@ge-af does SDK have retry mechanism for this?

**Comment by Norfeldt** [comment]
@ge-af would it be possible to keep this issue open until it has been fixed (and then close it)?

**Comment by VaidyaAkhil-Groww** [comment]
Hello, please revert on this issue, a large number of our users  are also facing this (~ 200K events with ~60K users impacted)
We have found no correlation with Devices, OS, OS versions, manufacturers, and others.

Can we check on AppsFlyer's end how many such requests are failing 

Different error messages that we are getting:

```
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

    Failed to connect to inapps.appsflyer.com/:::443

    Unable to resolve host "inapps.appsflyer.com": No address associated with hostname

    failed to connect to inapps.appsflyer.com/18.161.125.129 (port 443) from /56.198.3.219 (port 45040) after 10000ms
```

**Comment by gestshb** [comment]
Sure, here is the rewritten answer with the addition of "finally a solve my problem":

Hi,

I'm having the same issue as you. I contacted support and they said that the Connection error 443 is most likely an issue with the internet connection. This is usually a networking problem on the device itself. The device on which the test is performed doesn't have a valid internet connection, or the request fails due to DNS issues.

They also said that they have seen cases where the network prevents connecting to the AppsFlyer server. Please check the network connection/VPN connection (if using) and make sure that Adblocker or Firewall is not preventing access.

Here are some additional steps you can try:

Restart your device.
Check your internet connection.
Disable any Adblockers or Firewalls.
Try using a different browser.
Try using a different device.
If you are still having problems, please contact support again.

Finally, a solve my problem! I was able to fix the issue by disabling my Adblocker. I hope this helps you as well.

**Comment by VaidyaAkhil-Groww** [comment]
We also connected with the AppsFlyer team for the same issue. And were able to reproduce it using any Adblocker.
However, this was not a fatal issue for us (App did not crash and the user wasn't blocked in any way), hence we suppressed the issue at our end

**Comment by NarayanFH** [comment]
Issue, is still there for a specific device. I don't know how the IP or DNS is not valid to get the response of:
Failed to connect to zf8phv-cdn-settings.appsflyersdk.com/:::443

**Comment by glockjt** [comment]
Same issue here, has there been any update @ge-af? TIA

**Comment by DominikVavra** [comment]
Is there anything new about this problem ? Its 2024 and it seems that problem is still here.

Framework: React native
Appsflyer version: 6.9.2

Error: 
```
"Unable to resolve host \"inapps.appsflyer.com\": No address associated with hostname"
"Failed to connect to inapps.appsflyer.com/0.0.0.0:443"
```

Its still the same scenario. App is doing several API requests at the same time as AppsFlyer SDK inicialization. All other requests are OK (200) except appsflyer one. Our sentry is full of these errors. Hundreds per day. Is there any new solution we can try ? 

I don't want accept the answer that it is a network issue. As i said - ALL other requests are fine. There is no retry mechanism ? so it will try to reach the url few times and after that it will fire the error? Or can we somehow suppress the error? Make it warning only. 

Thank you

**Comment by miladdev85** [comment]
Why is this closed? My Sentry looks awful because of this. I think it's only present on Androids. Don't know if users have adblock or something else that blocks appsflyersdk.com but this issue should not be closed...

**Comment by MaorShiri** [comment]
still getting error in 2026 january

**Comment by HarshitMadhav** [comment]
facing the same issue for android, running the appsflyer version 6.17.8
