### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by jonathanroze** [AppsFlyerSDK/appsflyer-react-native-plugin#329]
# Report

## Plugin Version

react-native-appsflyer@^6.4.0

## On what Platform are you having the issue?

iOS and Android

## What happened?

Hi,

I implemented Appsflyer to follow my ads campaigns but since I installed Appsflyer I've a lot of network issues.

- `com.appsflyer.sdk.network`

When I trigger `appsFlyer.logEvent(...)`

Lot of `Unable to resolve host "inapps.appsflyer.com": No address associated with hostname`
and `Failed to connect to inapps.appsflyer.com/127.1.1.1:443`

My init Appsflyer code

```
    appsFlyer.setOneLinkCustomDomains(['winagain.onelink.me'], () => {}, () => {});

      onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
        (res) => {
          ....
        },
      );

      appsFlyer.initSdk(
        {
          devKey: 'myDevKey',
          isDebug: false,
          appId: 'myIosAppId',
          onInstallConversionDataListener: true, // Optional
          onDeepLinkListener: true, // Optional
          timeToWaitForATTUserAuthorization: 10, // for iOS 14.5
        },
        (result) => {
          console.log(result);
        },
        (error) => {
          console.error(error);
        },
      );

```

Please, help me to resolve these issues, or explain my they happen.

Thanks

**Comment by amit-kremer93** [comment]
Hi @jonathanroze Thank you for reaching out to us.
Be sure that you have internet connection and you registered your app properly in your AppsFlyer dashboard.
If the problem continues, please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, production steps, logs, code snippets, and any additional relevant information.

**Comment by ge-af** [comment]
Hi @jonathanroze 

Let me elaborate a bit on what @amit-kremer93 wrote.

This issue seems like a connection issue that was caused on the device itself and not in direct contact with our SDK logic.
It's most likely the result of an adBlocker such as [AdAway](https://adaway.org/) or [AdGuard](https://adguard.com/en/adguard-android/overview.html) or some DNS resolving issue that are interfere with our API being sent to the Server at that moment.

We do have a caching mechanism inside the SDK that allow up to 40 events to be cached, if needed, and it will flush them once the internet connection become stable again so it should be covered.

If you still have more questions about the current issue, we would kindly ask you to submit a support ticket to support@appsflyer.com ,as mentioned above, so we can provide optimal support.
