### ISSUE TITLE
dependency.platforms.ios.podspecPath is not allowed

### ISSUE THREAD

**Issue by smart04240** [AppsFlyerSDK/appsflyer-react-native-plugin#524]
# Report
warn Package react-native-appsflyer contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

## Plugin Version
6.12.2

## On what Platform are you having the issue?

ios

## What did you do?

npm run ios

**Comment by onamfc** [comment]
@smart04240 I have to use a patch until the issue is resolved. Here is a patch file for the v6.12.2 that you can use with the "patch-package" npm package

[react-native-appsflyer+6.12.2.patch](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/files/14225895/react-native-appsflyer%2B6.12.2.patch)

Also, it looks like there is an outstanding PR for the same issue.  https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/434 for more details.
